server:
  port: 8081

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://106.55.23.102:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.cst.springbootmybatis.domain
  #type-aliases-package指映射实体的包，好处在mapping.xml文件中指明type地址就不需要全类名

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
